# Python Pandas: รวม Sheet ใน Excel ด้วย Python Pandas #6

**คำอธิบาย:** ใน Notebook นี้คุณจะเรียนรู้วิธีรวม Sheet ใน Excel ด้วย Python Pandas

In [ ]:
# ✅ ติดตั้งอัตโนมัติ: ติดตั้งเฉพาะเมื่อยังไม่มี package
try:
    import pandas
    import openpyxl
    print("✅ ติดตั้ง packages ทั้งหมดแล้ว")
except ImportError:
    %pip install pandas openpyxl

Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.13/site-packages (2.2.3)
Requirement already satisfied: openpyxl in /opt/anaconda3/lib/python3.13/site-packages (3.1.5)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: et_xmlfile in /opt/anaconda3/lib/python3.13/site-packages (from openpyxl) (1.1.0)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
# 📦 นำเข้า pandas — เครื่องมือหลักสำหรับอ่าน รวม และส่งออกข้อมูล Excel
import pandas as pd

## ขั้นตอนที่ 1: ตรวจสอบไฟล์ Excel ต้นทาง
โหลดและตรวจสอบไฟล์ Excel ที่มีหลาย sheet

In [ ]:
# 📥 ดาวน์โหลดไฟล์ข้อมูลจาก GitHub (ถ้ายังไม่มี)
# ไฟล์นี้มีข้อมูลแยกอยู่ในหลาย sheet — เหมาะสำหรับฝึกรวมข้อมูล
import requests
import os

url = "https://raw.githubusercontent.com/AbhisheakSaraswat/RawData/main/Splited%20Raw%20Data.xlsx"
file_path = "Splited Raw Data.xlsx"

if os.path.exists(file_path):
    print(f"✅ {file_path} มีอยู่แล้ว ข้ามการดาวน์โหลด")
else:
    print("📥 ไม่พบไฟล์ กำลังดาวน์โหลด...")
    r = requests.get(url)
    r.raise_for_status()  # แสดง error ถ้าดาวน์โหลดไม่สำเร็จ
    with open(file_path, "wb") as f:
        f.write(r.content)
    print("✅ ดาวน์โหลดไฟล์สำเร็จ")

# 📋 โหลดไฟล์ Excel แล้วตรวจสอบว่ามี sheet อะไรบ้าง
xls = pd.ExcelFile(file_path)
print(f"\nSheet ที่มีอยู่: {xls.sheet_names}")
print(f"จำนวน sheet: {len(xls.sheet_names)}")

File downloaded successfully
Available sheets: ['New York', 'New Jersey', 'Washington', 'Massachusetts', 'Oregon', 'California', 'Connecticut', 'Nevada']
Number of sheets: 8

## ขั้นตอนที่ 2: อ่านทุก Sheet เป็น DataFrame
อ่านแต่ละ sheet แล้วแสดงตัวอย่าง

In [ ]:
# 📖 อ่านทุก sheet ในครั้งเดียวเป็น dictionary: {ชื่อ_sheet: DataFrame}
# sheet_name=None บอก pandas ให้อ่านทุก sheet
all_sheets = pd.read_excel(file_path, sheet_name=None)

# 🔍 แสดงสรุปแต่ละ sheet (ชื่อ, จำนวนแถว, จำนวนคอลัมน์)
for sheet_name, df in all_sheets.items():
    print(f"Sheet: '{sheet_name}' -> {df.shape[0]} แถว, {df.shape[1]} คอลัมน์")

Sheet: 'New York' -> 1295 rows, 9 columns
Sheet: 'New Jersey' -> 762 rows, 9 columns
Sheet: 'Washington' -> 813 rows, 9 columns
Sheet: 'Massachusetts' -> 1206 rows, 9 columns
Sheet: 'Oregon' -> 564 rows, 9 columns
Sheet: 'California' -> 567 rows, 9 columns
Sheet: 'Connecticut' -> 335 rows, 9 columns
Sheet: 'Nevada' -> 142 rows, 9 columns

## ขั้นตอนที่ 3: รวมทุก Sheet เป็น DataFrame เดียว
ใช้ `pd.concat()` เพื่อรวมทุก sheet

In [ ]:
# 🔗 รวมทุก sheet เป็น DataFrame เดียวด้วย pd.concat()
# .values() ให้ list ของ DataFrame (หนึ่งตัวต่อ sheet)
# ignore_index=True รีเซ็ตเลขแถว (0, 1, 2...) แทนที่จะเก็บ index เดิม
combined_df = pd.concat(all_sheets.values(), ignore_index=True)

print(f"ขนาด DataFrame รวม: {combined_df.shape}")
combined_df.head()

Combined DataFrame shape: (5684, 9)

,Sales Representative,Location,Region,Customer,Order Date,Product,Quantity,Price,Total Sale Amount
0,Sara Snyder,New York,East,Raymond Young,2016-01-01 00:00:00,"Bravo II Megaboss 12-Amp Hard Body Upright, Re...",6,12.42,74.52
1,Sara Snyder,New York,East,Christina Little,2016-01-01 00:00:00,Newell 322,6,53.35,320.10
2,Randy Watson,New York,East,Ruby Matthews,2016-01-02 00:00:00,DXL Angle-View Binders with Locking Rings by S...,6,17.83,106.98
3,Sara Snyder,New York,East,Christopher Oliver,2016-01-02 00:00:00,Belkin F5C206VTEL 6 Outlet Surge,8,12.42,99.36
4,Sara Snyder,New York,East,Gloria Harper,2016-01-02 00:00:00,Holmes Replacement Filter for HEPA Air Cleaner...,8,16.32,130.56

## ขั้นตอนที่ 4: บันทึกข้อมูลที่รวมแล้ว
ส่งออก DataFrame รวมเป็นไฟล์ Excel ใหม่

In [ ]:
# 💾 บันทึกข้อมูลรวมเป็นไฟล์ Excel ใหม่
# engine='openpyxl' ถูกใช้โดยอัตโนมัติสำหรับไฟล์ .xlsx
output_file = "Combined_Data.xlsx"
combined_df.to_excel(output_file, index=False, sheet_name='Combined')
print(f"✅ บันทึกข้อมูลรวมไปที่: {output_file}")
print(f"จำนวนแถวรวม: {len(combined_df)}")

✅ Combined data saved to: Combined_Data.xlsx
Total rows: 5684

## ทางเลือก: รวม Sheet พร้อมเพิ่มคอลัมน์ชื่อ Sheet ต้นทาง
เพิ่มคอลัมน์ระบุว่าแต่ละแถวมาจาก sheet ไหน

In [ ]:
# 🏷️ รวมพร้อมคอลัมน์ "Source_Sheet" เพื่อรู้ว่าแต่ละแถวมาจาก sheet ไหน
# มีประโยชน์สำหรับการตรวจสอบย้อนกลับ — สามารถติดตามข้อมูลกลับไปที่ต้นทางได้
dfs_with_source = []
for sheet_name, df in all_sheets.items():
    df['Source_Sheet'] = sheet_name  # เพิ่มคอลัมน์ชื่อ sheet ต้นทาง
    dfs_with_source.append(df)

combined_with_source = pd.concat(dfs_with_source, ignore_index=True)
print(f"ข้อมูลรวมพร้อมคอลัมน์ต้นทาง: {combined_with_source.shape}")
combined_with_source.head()

Combined with source column: (5684, 10)

,Sales Representative,Location,Region,Customer,Order Date,Product,Quantity,Price,Total Sale Amount,Source_Sheet
0,Sara Snyder,New York,East,Raymond Young,2016-01-01 00:00:00,"Bravo II Megaboss 12-Amp Hard Body Upright, Re...",6,12.42,74.52,New York
1,Sara Snyder,New York,East,Christina Little,2016-01-01 00:00:00,Newell 322,6,53.35,320.10,New York
2,Randy Watson,New York,East,Ruby Matthews,2016-01-02 00:00:00,DXL Angle-View Binders with Locking Rings by S...,6,17.83,106.98,New York
3,Sara Snyder,New York,East,Christopher Oliver,2016-01-02 00:00:00,Belkin F5C206VTEL 6 Outlet Surge,8,12.42,99.36,New York
4,Sara Snyder,New York,East,Gloria Harper,2016-01-02 00:00:00,Holmes Replacement Filter for HEPA Air Cleaner...,8,16.32,130.56,New York

## รวมหลายไฟล์ Excel จากโฟลเดอร์
โบนัส: ถ้าคุณมีหลายไฟล์ Excel ในโฟลเดอร์เดียวกัน

In [ ]:
# 📁 โบนัส: รวมหลายไฟล์ Excel จากโฟลเดอร์ (ไม่ใช่แค่ sheet แต่เป็นทั้งไฟล์)
# มีประโยชน์เมื่อได้รับหลายรายงาน (เช่น ม.ค..xlsx, ก.พ..xlsx ฯลฯ)
import glob
import os

folder_path = "./data/"  # 📂 เปลี่ยน path นี้เป็นโฟลเดอร์ของคุณ

# 🔍 ค้นหาไฟล์ .xlsx ทั้งหมดในโฟลเดอร์
excel_files = glob.glob(os.path.join(folder_path, "*.xlsx"))
print(f"พบ {len(excel_files)} ไฟล์ Excel")

if excel_files:
    all_dfs = []
    for file in excel_files:
        df = pd.read_excel(file)
        df['Source_File'] = os.path.basename(file)  # ติดตามว่าแต่ละแถวมาจากไฟล์ไหน
        all_dfs.append(df)
    
    combined = pd.concat(all_dfs, ignore_index=True)
    print(f"จำนวนแถวรวมทั้งหมด: {len(combined)}")

    output_file = os.path.join(folder_path, "combined_output.xlsx")
    combined.to_excel(output_file, index=False)

    print(f"✅ บันทึกไฟล์รวม: {output_file}")

Found 2 Excel files
Total combined rows: 11368
Saved combined file: ./data/combined_output.xlsx

---

## 🎮 Mini Project: รวมข้อมูลจากหลาย Sheet

ทดสอบการรวมข้อมูล Excel ด้วย pandas!

> 💡 **คำตอบ:** ดูไฟล์ `answers/08_answers.ipynb`

---

### โจทย์ที่ 1: รวมทุก Sheet เป็น DataFrame เดียว 🟢
ใช้ไฟล์ที่สร้างจาก NB 07 (`products_by_category.xlsx` หรือ `Random Sales Data.xlsx`):
1. อ่านทุก Sheet ด้วย `pd.read_excel(sheet_name=None)`
2. เพิ่มคอลัมน์ `Source_Sheet` เพื่อบอกว่ามาจาก Sheet ไหน
3. รวมทุก DataFrame ด้วย `pd.concat()`
4. Print จำนวนแถวรวม + `value_counts()` ของ `Source_Sheet`

> 💡 Hint: `all_sheets = pd.read_excel(file, sheet_name=None)` → dict ของ DataFrames

In [ ]:
# โจทย์ที่ 1: รวมทุก Sheet เป็น DataFrame เดียว
# เขียนโค้ดของคุณที่นี่ 👇

### โจทย์ที่ 2: รวมไฟล์ + สรุปข้อมูล 🟡
1. ถ้ามีไฟล์ `sales_East.xlsx`, `sales_West.xlsx` จาก NB 07 — รวมเข้าด้วยกัน
   (ถ้าไม่มีให้สร้าง 2 ไฟล์ Excel จำลอง แต่ละไฟล์มี 5 แถว)
2. เพิ่มคอลัมน์ `Source_File` บอกว่ามาจากไฟล์ไหน
3. บันทึก DataFrame รวมเป็น `combined_sales.xlsx`
4. Print สรุป: จำนวนแถวรวม, จำนวนไฟล์ต้นทาง

> 💡 Hint: ใช้ `glob.glob('sales_*.xlsx')` + `os.path.basename()`

In [ ]:
# โจทย์ที่ 2: รวมไฟล์ + สรุปข้อมูล
# เขียนโค้ดของคุณที่นี่ 👇