# 📋 Notebook 14: JSON Basics — Excel ↔ JSON Conversion

## สิ่งที่จะได้เรียนรู้
- JSON คืออะไร? ใช้ทำอะไร?
- อ่าน/เขียน JSON ด้วย Python
- แปลง Excel → JSON
- แปลง JSON → Excel
- ใช้ JSON เก็บข้อมูล Lab results

---

### ทำไมต้องรู้จัก JSON?
เวลาเราส่งข้อมูลจาก Excel ไปเก็บในฐานข้อมูล (Database)  
มักจะต้องแปลงให้เป็นรูปแบบ **JSON** ก่อน เพราะ:
- Database เข้าใจ JSON
- API (เช่น FastAPI) รับ-ส่งข้อมูลเป็น JSON
- JSON อ่านง่าย ทั้งคนและคอมพิวเตอร์

## 1. JSON คืออะไร?

**JSON** = JavaScript Object Notation  
เป็นรูปแบบข้อมูลที่ใช้กันทั่วโลก มีหน้าตาแบบนี้:

```json
{
    "name": "Arsenic",
    "symbol": "As",
    "wavelength": 188.979,
    "unit": "mg/kg"
}
```

### เปรียบเทียบ Python Dictionary กับ JSON
| Python Dict | JSON |
|---|---|
| `True` / `False` | `true` / `false` |
| `None` | `null` |
| `'single quotes'` | `"double quotes"` only |
| เป็น object ใน memory | เป็น text/string |

In [1]:
import json  # json = ไลบรารีสำหรับอ่าน/เขียนข้อมูล JSON

# === Python Dictionary (โครงสร้างเก็บข้อมูลแบบ key-value) ===
element = {
    "name": "Arsenic",       # ชื่อธาตุ
    "symbol": "As",          # สัญลักษณ์ธาตุ
    "wavelength": 188.979,   # ความยาวคลื่น
    "unit": "mg/kg",         # หน่วยวัด
    "is_active": True,       # Python: True (จริง) / False (ไม่จริง)
    "notes": None             # Python: None = ไม่มีค่า (null)
}

print("Type:", type(element))  # แสดงประเภทข้อมูล
print("Dict:", element)        # แสดงข้อมูลทั้งหมด

Type: <class 'dict'>
Dict: {'name': 'Arsenic', 'symbol': 'As', 'wavelength': 188.979, 'unit': 'mg/kg', 'is_active': True, 'notes': None}

## 2. แปลง Python Dict → JSON String
ใช้ `json.dumps()` (dump **s**tring)

In [2]:
# แปลง Dict → JSON string
json_string = json.dumps(element, indent=2)

print("Type:", type(json_string))
print("JSON:")
print(json_string)

# สังเกต: True → true, None → null

Type: <class 'str'>
JSON:
{
  "name": "Arsenic",
  "symbol": "As",
  "wavelength": 188.979,
  "unit": "mg/kg",
  "is_active": true,
  "notes": null
}

## 3. แปลง JSON String → Python Dict
ใช้ `json.loads()` (load **s**tring)

In [3]:
# JSON string
json_text = '{"symbol": "Pb", "name": "Lead", "wavelength": 220.353}'

# แปลง JSON → Dict
data = json.loads(json_text)

print("Type:", type(data))
print("Symbol:", data["symbol"])
print("Wavelength:", data["wavelength"])

Type: <class 'dict'>
Symbol: Pb
Wavelength: 220.353

## 4. เขียน JSON ลงไฟล์ / อ่านจากไฟล์

In [4]:
import os
os.makedirs("output", exist_ok=True)

# ข้อมูลหลาย elements
elements = [
    {"symbol": "As", "name": "Arsenic", "wavelength": 188.979, "unit": "mg/kg"},
    {"symbol": "Pb", "name": "Lead", "wavelength": 220.353, "unit": "mg/kg"},
    {"symbol": "Cd", "name": "Cadmium", "wavelength": 226.502, "unit": "mg/kg"},
    {"symbol": "Hg", "name": "Mercury", "wavelength": 194.168, "unit": "mg/kg"},
]

# === เขียนลงไฟล์ ===
with open("output/elements.json", "w", encoding="utf-8") as f:
    json.dump(elements, f, indent=2, ensure_ascii=False)

print("✅ Saved to output/elements.json")

✅ Saved to output/elements.json

In [5]:
# === อ่านจากไฟล์ ===
with open("output/elements.json", "r", encoding="utf-8") as f:
    loaded = json.load(f)

print(f"Loaded {len(loaded)} elements:")
for elem in loaded:
    print(f"  {elem['symbol']}: {elem['name']} ({elem['wavelength']} nm)")

Loaded 4 elements:
  As: Arsenic (188.979 nm)
  Pb: Lead (220.353 nm)
  Cd: Cadmium (226.502 nm)
  Hg: Mercury (194.168 nm)

## 5. สร้างข้อมูลตัวอย่าง Excel (ICP Lab Data)

In [6]:
import pandas as pd
import numpy as np

# สร้างข้อมูลตัวอย่าง ICP Lab
np.random.seed(42)

data = {
    "sample_id": [f"S-{i:03d}" for i in range(1, 11)],
    "sample_name": [f"Sample {i}" for i in range(1, 11)],
    "As (mg/kg)": np.round(np.random.uniform(0.01, 5.0, 10), 3),
    "Pb (mg/kg)": np.round(np.random.uniform(0.05, 10.0, 10), 3),
    "Cd (mg/kg)": np.round(np.random.uniform(0.01, 2.0, 10), 3),
    "Hg (mg/kg)": np.round(np.random.uniform(0.005, 1.0, 10), 3),
    "test_date": pd.date_range("2026-01-01", periods=10, freq="D"),
    "analyst": ["Dr. Smith"] * 5 + ["Dr. Jones"] * 5,
    "status": ["completed"] * 8 + ["pending"] * 2,
}

df = pd.DataFrame(data)
df.to_excel("output/lab_results.xlsx", index=False)
print("✅ Created lab_results.xlsx")
df.head()

✅ Created lab_results.xlsx

,sample_id,sample_name,As (mg/kg),Pb (mg/kg),Cd (mg/kg),Hg (mg/kg),test_date,analyst,status
0,S-001,Sample 1,1.879,0.255,1.228,0.610,2026-01-01,Dr. Smith,completed
1,S-002,Sample 2,4.754,9.701,0.288,0.175,2026-01-02,Dr. Smith,completed
2,S-003,Sample 3,3.663,8.333,0.591,0.070,2026-01-03,Dr. Smith,completed
3,S-004,Sample 4,2.997,2.163,0.739,0.949,2026-01-04,Dr. Smith,completed
4,S-005,Sample 5,0.789,1.859,0.918,0.966,2026-01-05,Dr. Smith,completed

## 6. แปลง Excel → JSON (หลายวิธี)

In [7]:
# อ่าน Excel
df = pd.read_excel("output/lab_results.xlsx")

# === วิธี 1: to_json() — ทั้ง DataFrame ===
json_records = df.to_json(orient="records", date_format="iso", force_ascii=False)

# แสดง 2 records แรก
records = json.loads(json_records)
print("วิธี 1: DataFrame → JSON records")
print(json.dumps(records[:2], indent=2, ensure_ascii=False))

วิธี 1: DataFrame → JSON records
[
  {
    "sample_id": "S-001",
    "sample_name": "Sample 1",
    "As (mg/kg)": 1.879,
    "Pb (mg/kg)": 0.255,
    "Cd (mg/kg)": 1.228,
    "Hg (mg/kg)": 0.61,
    "test_date": "2026-01-01T00:00:00.000",
    "analyst": "Dr. Smith",
    "status": "completed"
  },
  {
    "sample_id": "S-002",
    "sample_name": "Sample 2",
    "As (mg/kg)": 4.754,
    "Pb (mg/kg)": 9.701,
    "Cd (mg/kg)": 0.288,
    "Hg (mg/kg)": 0.175,
    "test_date": "2026-01-02T00:00:00.000",
    "analyst": "Dr. Smith",
    "status": "completed"
  }
]

In [8]:
# === วิธี 2: to_dict() — แปลงเป็น Dict ก่อน ===
dict_records = df.to_dict(orient="records")

print("วิธี 2: DataFrame → Dict → JSON")
print(f"Type: {type(dict_records)}")
print(f"First record: {dict_records[0]}")

วิธี 2: DataFrame → Dict → JSON
Type: <class 'list'>
First record: {'sample_id': 'S-001', 'sample_name': 'Sample 1', 'As (mg/kg)': 1.879, 'Pb (mg/kg)': 0.255, 'Cd (mg/kg)': 1.228, 'Hg (mg/kg)': 0.61, 'test_date': Timestamp('2026-01-01 00:00:00'), 'analyst': 'Dr. Smith', 'status': 'completed'}

In [9]:
# === วิธี 3: สร้าง JSON structure แบบกำหนดเอง ===
# แบบนี้ใช้บ่อยในงานจริง เพราะควบคุมรูปแบบได้

lab_report = {
    "report_info": {
        "generated_at": pd.Timestamp.now().isoformat(),
        "total_samples": len(df),
        "file_source": "lab_results.xlsx"
    },
    "elements": ["As", "Pb", "Cd", "Hg"],
    "samples": []
}

for _, row in df.iterrows():
    sample = {
        "sample_id": row["sample_id"],
        "sample_name": row["sample_name"],
        "concentrations": {
            "As": float(row["As (mg/kg)"]),
            "Pb": float(row["Pb (mg/kg)"]),
            "Cd": float(row["Cd (mg/kg)"]),
            "Hg": float(row["Hg (mg/kg)"]),
        },
        "test_date": str(row["test_date"]),
        "analyst": row["analyst"],
        "status": row["status"]
    }
    lab_report["samples"].append(sample)

# บันทึก
with open("output/lab_report.json", "w", encoding="utf-8") as f:
    json.dump(lab_report, f, indent=2, ensure_ascii=False)

print("✅ Custom JSON structure saved!")
print(json.dumps(lab_report["samples"][0], indent=2))

✅ Custom JSON structure saved!
{
  "sample_id": "S-001",
  "sample_name": "Sample 1",
  "concentrations": {
    "As": 1.879,
    "Pb": 0.255,
    "Cd": 1.228,
    "Hg": 0.61
  },
  "test_date": "2026-01-01 00:00:00",
  "analyst": "Dr. Smith",
  "status": "completed"
}

## 7. แปลง JSON → Excel

In [10]:
# อ่าน JSON กลับมา
with open("output/lab_report.json", "r", encoding="utf-8") as f:
    report = json.load(f)

print(f"Report has {report['report_info']['total_samples']} samples")
print(f"Elements: {report['elements']}")

# แปลง samples กลับเป็น DataFrame
rows = []
for s in report["samples"]:
    row = {
        "sample_id": s["sample_id"],
        "sample_name": s["sample_name"],
        "test_date": s["test_date"],
        "analyst": s["analyst"],
        "status": s["status"],
    }
    # เพิ่ม concentrations เป็นคอลัมน์
    for elem, value in s["concentrations"].items():
        row[f"{elem} (mg/kg)"] = value
    rows.append(row)

df_from_json = pd.DataFrame(rows)
df_from_json.to_excel("output/from_json_report.xlsx", index=False)
print("\n✅ Saved back to Excel!")
df_from_json.head()

Report has 10 samples
Elements: ['As', 'Pb', 'Cd', 'Hg']

✅ Saved back to Excel!

,sample_id,sample_name,test_date,analyst,status,As (mg/kg),Pb (mg/kg),Cd (mg/kg),Hg (mg/kg)
0,S-001,Sample 1,2026-01-01 00:00:00,Dr. Smith,completed,1.879,0.255,1.228,0.610
1,S-002,Sample 2,2026-01-02 00:00:00,Dr. Smith,completed,4.754,9.701,0.288,0.175
2,S-003,Sample 3,2026-01-03 00:00:00,Dr. Smith,completed,3.663,8.333,0.591,0.070
3,S-004,Sample 4,2026-01-04 00:00:00,Dr. Smith,completed,2.997,2.163,0.739,0.949
4,S-005,Sample 5,2026-01-05 00:00:00,Dr. Smith,completed,0.789,1.859,0.918,0.966

## 8. Nested JSON — ข้อมูลซ้อนกัน

ในงานจริง JSON มักมีข้อมูลซ้อนกันหลายชั้น  
เหมือนกับที่เก็บใน Database column แบบ JSON

In [11]:
# ตัวอย่าง test_results จาก TestOrder ในระบบจริง
test_order = {
    "order_id": "ORD-2026-0001",
    "sample_id": "07952",
    "laboratory": "L66",
    "panel": "EU4",
    "test_results": {
        "elements": ["As", "Pb", "Cd", "Hg"],
        "samples": [
            {
                "sample_id": "S1",
                "replicate": 1,
                "concentrations": {
                    "As": 0.523,
                    "Pb": 1.245,
                    "Cd": 0.089,
                    "Hg": 0.034
                }
            },
            {
                "sample_id": "S1",
                "replicate": 2,
                "concentrations": {
                    "As": 0.534,
                    "Pb": 1.256,
                    "Cd": 0.091,
                    "Hg": 0.032
                }
            }
        ]
    }
}

# เข้าถึงข้อมูลซ้อน
print(f"Order: {test_order['order_id']}")
print(f"Elements: {test_order['test_results']['elements']}")

for sample in test_order['test_results']['samples']:
    print(f"\n  Sample {sample['sample_id']} (Rep {sample['replicate']}):")
    for elem, conc in sample['concentrations'].items():
        print(f"    {elem}: {conc} mg/kg")

Order: ORD-2026-0001
Elements: ['As', 'Pb', 'Cd', 'Hg']

  Sample S1 (Rep 1):
    As: 0.523 mg/kg
    Pb: 1.245 mg/kg
    Cd: 0.089 mg/kg
    Hg: 0.034 mg/kg

  Sample S1 (Rep 2):
    As: 0.534 mg/kg
    Pb: 1.256 mg/kg
    Cd: 0.091 mg/kg
    Hg: 0.032 mg/kg

In [12]:
# แปลง nested JSON → flat DataFrame (สำหรับวิเคราะห์)
flat_rows = []
for sample in test_order['test_results']['samples']:
    for elem, conc in sample['concentrations'].items():
        flat_rows.append({
            "order_id": test_order["order_id"],
            "sample_id": sample["sample_id"],
            "replicate": sample["replicate"],
            "element": elem,
            "concentration": conc,
        })

df_flat = pd.DataFrame(flat_rows)
print("Flat DataFrame (for analysis):")
df_flat

Flat DataFrame (for analysis):

        order_id sample_id  replicate element  concentration
0  ORD-2026-0001        S1          1      As          0.523
1  ORD-2026-0001        S1          1      Pb          1.245
2  ORD-2026-0001        S1          1      Cd          0.089
3  ORD-2026-0001        S1          1      Hg          0.034
4  ORD-2026-0001        S1          2      As          0.534
5  ORD-2026-0001        S1          2      Pb          1.256
6  ORD-2026-0001        S1          2      Cd          0.091
7  ORD-2026-0001        S1          2      Hg          0.032

## 📝 สรุป

| Function | ใช้ทำอะไร |
|---|---|
| `json.dumps(data)` | Dict → JSON string |
| `json.loads(text)` | JSON string → Dict |
| `json.dump(data, file)` | Dict → JSON file |
| `json.load(file)` | JSON file → Dict |
| `df.to_json()` | DataFrame → JSON |
| `df.to_dict()` | DataFrame → Dict |
| `pd.DataFrame(list)` | List of Dict → DataFrame |

### Next: Notebook 15 — การเชื่อมต่อ Database (PostgreSQL)

---

## 🎮 Mini Project: ระบบจัดการข้อมูลพนักงาน (JSON)

ทดสอบการใช้ JSON กับ Python!

> 💡 **คำตอบ:** ดูไฟล์ `answers/14_answers.ipynb`

---

### โจทย์ที่ 1: สร้าง JSON ข้อมูลพนักงาน 🟢
1. สร้าง dictionary ข้อมูลพนักงาน 3 คน (ชื่อ, แผนก, เงินเดือน, ทักษะ 3 อย่าง)
2. แปลงเป็น JSON string ด้วย `json.dumps()` (indent=2, ensure_ascii=False)
3. บันทึกเป็นไฟล์ `employees.json`
4. อ่านกลับมาด้วย `json.load()` แล้ว print ชื่อพนักงานคนที่ 2

> 💡 Hint: ใช้ list ของ dict (nested structure)

In [ ]:
# โจทย์ที่ 1: สร้าง JSON ข้อมูลพนักงาน
# เขียนโค้ดของคุณที่นี่ 👇

### โจทย์ที่ 2: แปลง Excel → JSON → Excel 🟡
1. อ่าน `Random Sales Data.xlsx` ด้วย `pd.read_excel()`
2. แปลงเป็น JSON: `df.to_json(orient='records')` บันทึกเป็น `sales_data.json`
3. อ่าน JSON กลับมาเป็น DataFrame
4. ตรวจสอบว่า shape เท่ากับ DataFrame เดิม
5. บันทึกเป็น `sales_from_json.xlsx`

> 💡 Hint: Excel → `to_dict('records')` → `json.dump()` → `json.load()` → `pd.DataFrame()`

In [ ]:
# โจทย์ที่ 2: Excel → JSON → Excel
# เขียนโค้ดของคุณที่นี่ 👇